openapi: 3.0.1

info:
  title: will be replaced
  description: This information will be replaced by the SpringFox config information
  version: 0.0.1

servers:
  - url: /

paths:
  /videos:
    post:
      tags:
        - video-controller
      summary: 'Initial path, please replace this'
      operationId: initialPath
      responses:
        404:
          description: NOT FOUND - not defined yet
      security:
        - Bearer: [ ]

components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header